### ISSUE TITLE
Local exec provisioner -- 

### ISSUE THREAD

**Issue by onenessboy** [murggu/azure-synapse-terraform#1]
Hi Aitor,

I am getting below error while deploying synapse environment using this repo 
error: Please run 'az login' to setup account.

I am using microsoft hosted agent(windows) to run this setup

![image](https://user-images.githubusercontent.com/37249391/167829459-7802cd67-1dbb-49b0-bd82-72141a1a3a17.png)

Can you please help

**Comment by murggu** [comment]
@onenessboy Thanks for posting this issue. You´re right - if you try to run this code from github actions and/or ado pipelines, you´ll get that issue. 

You can do two things:

1. Comment/remove the managed endpoint auto approval steps, so you will make the deployment work from your pipelines and you can then approve them manually.
2. Switch to ARM, calling ARM code from terraform using `template_content`

**Comment by onenessboy** [comment]
Thanks , it helped
